### ISSUE TITLE
Scope restricted to web?

### ISSUE THREAD

**Issue by SpaceGnome** [antifraudcg/antifraudcg.github.io#4]
Looking at https://raw.githack.com/antifraudcg/antifraudcg.github.io/d0975a36de0f004cc5a32960a67892516422a368/charter.html it says:

`The Community Group will discuss and document various forms of fraudulent activity on the web, to establish a foundation for developing web APIs that assist in our mission.`

Is this CG just restricted to web browser fraud & abuse? What about webview, mobile app, CTV, etc... fraud & abuse?

**Comment by dvorak42** [comment]
Updated some of the wording to be a little clearer here based on the last CG meeting. I'll close this issue in a few days unless you think it still needs some wordsmithing?
